### ISSUE TITLE
Replace auth info in .env files with secrets

### ISSUE THREAD

**Issue by surchs** [neurobagel/recipes#33]
Right now we recommend having the DB user/password inside of the .env file. The docker-compose recommendation is to instead use secrets: https://docs.docker.com/compose/use-secrets/

We can make docker compose [read in secrets from the environment vars](https://docs.docker.com/compose/compose-file/09-secrets/#example-2) set in the existing `.env` file. For more separation, we could specify a second .env to hold just the sensitive variables (e.g., `secrets.env`) which we could pass to the docker compose CLI when launching the stack.

One complication with Docker secrets is that they end up in the container as contents of `/run/secrets` files (one secret per file). 

To ensure our apps using the DB credentials (GraphDB, n-API) can still easily access the values of the secrets without having to modify source code to parse file paths, we could update the entrypoints for the GraphDB and n-API containers to include bash code to store the secret file contents as environment variables, e.g.:

```bash
NB_GRAPH_PASSWORD=$(cat /run/secrets/db_password)
```

This should enable them to be accessed as they currently are inside the app code.

See more notes on using secrets in our internal wiki: https://hackmd.io/@neurobagel/HyGSQ-Ip6#Using-secrets-in-Docker-Compose

**Comment by alyssadai** [comment]
Updated the issue description @surchs - let me know wyt!
