### ISSUE TITLE
Profile-specific values of query tool environment variable `NB_IS_FEDERATION_API`

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/recipes#36]
### Description

`NB_IS_FEDERATION_API` is now needed by the query tool to determine what kind of API it's talking to, with the default being a federation API.

### Additional details

The following need to be updated:
- [ ] ~environment variable table~
- [ ] ~full-stack .env file~
- [ ] full-stack docker-compose.yml

*ALSO, note that the `local_node` profile query tool won't work unless this is explicitly set. Thus

- [ ] Confirm you can launch a `local_node` profile with a query tool in `non-federation` mode via docker compose up

**Comment by surchs** [comment]
I think this is the issue where we said we could use the docker compose `extends` syntax: https://docs.docker.com/compose/multiple-compose-files/extends/#extending-services-within-the-same-file
