### ISSUE TITLE
Environment variable for mounted GraphDB home directory not used

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/recipes#38]
The setup script includes a line to set the graphDB home inside the container to a directory `/opt/graphdb`,

https://github.com/neurobagel/recipes/blob/b5cf9d86529c43091e7df0c4810d41f3698a2adc/dev/setup.sh#L3

but this hardcoded path is both different from the default path for the home directory inside the container (`/opt/graphdb/home`) which is mounted, and also does not use the configurable variable for the container home directory, `$NB_GRAPH_ROOT_CONT`

https://github.com/neurobagel/recipes/blob/b5cf9d86529c43091e7df0c4810d41f3698a2adc/dev/docker-compose.yml#L30

as a result, the actual mounted host path ${NB_GRAPH_ROOT_**HOST**} never gets any contents, because the container path  it is pointing to (`/opt/graphdb/home` by default) is not the home directory inside the container that is actually being used. This currently means that when the containers are spun down, all the data/configuration for the GraphDB server is erased.

To resolve this, we should for now 

- [x] replace `/opt/graphdb/` in the setup.sh with a reference to the variable ${NB_GRAPH_ROOT_CONT} 

(in future, we may want to remove this variable altogether - but we should still ensure that the actual mounted path is correct with what's used in the setup.sh script.

**Comment by surchs** [comment]
@alyssadai are you referring to `NB_GRAPH_ROOT_HOST` here? i.e. setting `NB_GRAPH_ROOT_HOST` in the `.env` file to something other than `~/graphdb-home` has no effect and the graph service still starts with `~/graphdb-home`?

**Comment by alyssadai** [comment]
Forgot to reply - I updated the description with more details yesterday :) hope that helps!
