### ISSUE TITLE
Update default/recommended Docker image tag for services

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/recipes#9]
`latest` -> `stable`?

- can we have `latest` as a synonym (for `nightly` or `stable`)?
- what happens when there's no `latest` tag?
  - if you docker pull an image w/o specifying the tag, but there's no `latest` tag in the remote repo, Docker will error out

**Comment by surchs** [comment]
decision: stable is replaced by `latest` (again). latest means latest release

**Comment by alyssadai** [comment]
Given above decision to stick with using the `latest` tag for the latest stable release, no changes are needed to the templates in this repo.
